// Demo data for a Kodaikanal-based host offering multiple services
// Used as fallback when real data is empty for testing the host dashboard

import type { Stay, Car, Bike, Experience, Booking, Profile } from '@/types/database';

// Demo listing images
import mistyValleyCottage from '@/assets/demo/misty-valley-cottage.jpg';
import hilltopHeritageBungalow from '@/assets/demo/hilltop-heritage-bungalow.jpg';
import pineForestTreehouse from '@/assets/demo/pine-forest-treehouse.jpg';
import swiftDzire from '@/assets/demo/swift-dzire.jpg';
import mahindraThar from '@/assets/demo/mahindra-thar.jpg';
import royalEnfieldClassic from '@/assets/demo/royal-enfield-classic.jpg';
import hondaActiva from '@/assets/demo/honda-activa.jpg';
import ktmDuke from '@/assets/demo/ktm-duke.jpg';
import sunriseTrek from '@/assets/demo/sunrise-trek.jpg';
import lakeCycling from '@/assets/demo/lake-cycling.jpg';
import stargazing from '@/assets/demo/stargazing.jpg';

const DEMO_HOST_ID = 'demo-host-kodaikanal';
const now = new Date().toISOString();
const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();
const daysFromNow = (n: number) => new Date(Date.now() + n * 86400000).toISOString();

export const DEMO_PROFILE: Partial<Profile> = {
  id: DEMO_HOST_ID,
  full_name: 'Karthik Rajan',
  phone: '+91 98765 43210',
  bio: 'Passionate host offering curated stays, rides, and experiences in the hills of Kodaikanal. 5+ years of hospitality experience.',
  city: 'Kodaikanal',
  state: 'Tamil Nadu',
  country: 'India',
  profile_image: null,
  created_at: daysAgo(730),
  updated_at: now,
};

export const DEMO_STAYS: Stay[] = [
  {
    id: 'demo-stay-1',
    host_id: DEMO_HOST_ID,
    title: 'Misty Valley Cottage',
    slug: 'misty-valley-cottage',
    description: 'A cozy 2-bedroom cottage nestled in the Kodaikanal hills with panoramic valley views, fireplace, and a private garden. Perfect for families and couples seeking tranquility.',
    location: 'Kodaikanal, Tamil Nadu',
    price_per_night: 3500,
    max_guests: 6,
    bedrooms: 2,
    bathrooms: 2,
    property_type: 'Cottage',
    amenities: ['Wi-Fi', 'Fireplace', 'Kitchen', 'Parking', 'Garden', 'Hot Water', 'Mountain View'],
    images: [mistyValleyCottage],
    availability_status: true,
    is_verified: true,
    verified_by: null,
    featured: true,
    rating: 4.8,
    total_reviews: 47,
    views_count: 1240,
    booking_count: 89,
    check_in_time: '14:00',
    check_out_time: '11:00',
    cancellation_policy: 'Free cancellation up to 48 hours before check-in',
    tags: ['hill-station', 'family-friendly', 'valley-view'],
    currency: 'INR',
    latitude: 10.2381,
    longitude: 77.4892,
    discounts: null,
    last_booked_at: daysAgo(2),
    created_at: daysAgo(365),
    updated_at: daysAgo(5),
  },
  {
    id: 'demo-stay-2',
    host_id: DEMO_HOST_ID,
    title: 'Hilltop Heritage Bungalow',
    slug: 'hilltop-heritage-bungalow',
    description: 'A stunning colonial-era bungalow at 7,000 ft elevation with 3 spacious bedrooms, antique furnishings, and breathtaking sunrise views over Kodaikanal Lake.',
    location: 'Kodaikanal, Tamil Nadu',
    price_per_night: 6500,
    max_guests: 8,
    bedrooms: 3,
    bathrooms: 3,
    property_type: 'Bungalow',
    amenities: ['Wi-Fi', 'Fireplace', 'Kitchen', 'Parking', 'Caretaker', 'BBQ', 'Lake View', 'Antique Décor'],
    images: [hilltopHeritageBungalow],
    availability_status: true,
    is_verified: true,
    verified_by: null,
    featured: false,
    rating: 4.9,
    total_reviews: 32,
    views_count: 890,
    booking_count: 54,
    check_in_time: '14:00',
    check_out_time: '11:00',
    cancellation_policy: 'Free cancellation up to 72 hours before check-in',
    tags: ['heritage', 'luxury', 'lake-view'],
    currency: 'INR',
    latitude: 10.2350,
    longitude: 77.4920,
    discounts: { weekly: 10 },
    last_booked_at: daysAgo(1),
    created_at: daysAgo(300),
    updated_at: daysAgo(3),
  },
  {
    id: 'demo-stay-3',
    host_id: DEMO_HOST_ID,
    title: 'Pine Forest Treehouse',
    slug: 'pine-forest-treehouse',
    description: 'A unique treehouse experience amid tall pine trees. Elevated deck, glass walls, and a stargazing roof — an unforgettable stay for adventurous souls.',
    location: 'Kodaikanal, Tamil Nadu',
    price_per_night: 4200,
    max_guests: 3,
    bedrooms: 1,
    bathrooms: 1,
    property_type: 'Treehouse',
    amenities: ['Stargazing Roof', 'Deck', 'Hot Water', 'Nature Trail', 'Breakfast Included'],
    images: [pineForestTreehouse],
    availability_status: true,
    is_verified: false,
    verified_by: null,
    featured: true,
    rating: 4.7,
    total_reviews: 18,
    views_count: 650,
    booking_count: 28,
    check_in_time: '15:00',
    check_out_time: '10:00',
    cancellation_policy: 'Non-refundable',
    tags: ['unique', 'couples', 'treehouse', 'adventure'],
    currency: 'INR',
    latitude: 10.2400,
    longitude: 77.4850,
    discounts: null,
    last_booked_at: daysAgo(5),
    created_at: daysAgo(180),
    updated_at: daysAgo(10),
  },
];

export const DEMO_CARS: Car[] = [
  {
    id: 'demo-car-1',
    host_id: DEMO_HOST_ID,
    title: 'Maruti Suzuki Swift Dzire',
    slug: 'maruti-swift-dzire-kodaikanal',
    description: 'Well-maintained sedan, ideal for Kodaikanal hill drives. Smooth automatic transmission with excellent mileage. GPS included.',
    location: 'Kodaikanal, Tamil Nadu',
    price_per_day: 1800,
    brand: 'Maruti Suzuki',
    model: 'Swift Dzire',
    year: 2023,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    seating_capacity: 5,
    vehicle_type: 'Sedan',
    mileage_limit: 200,
    amenities: ['GPS', 'Bluetooth', 'AC', 'USB Charging', 'First Aid Kit'],
    images: [swiftDzire],
    availability_status: true,
    is_verified: true,
    verified_by: null,
    featured: true,
    rating: 4.6,
    total_reviews: 35,
    views_count: 780,
    booking_count: 62,
    tags: ['sedan', 'automatic', 'hill-drive'],
    currency: 'INR',
    latitude: 10.2381,
    longitude: 77.4892,
    discounts: { weekly: 15 },
    last_booked_at: daysAgo(1),
    created_at: daysAgo(250),
    updated_at: daysAgo(2),
  },
  {
    id: 'demo-car-2',
    host_id: DEMO_HOST_ID,
    title: 'Mahindra Thar 4x4',
    slug: 'mahindra-thar-4x4-kodaikanal',
    description: 'Rugged 4x4 SUV perfect for off-road exploration around Kodaikanal. Hard-top convertible with powerful diesel engine.',
    location: 'Kodaikanal, Tamil Nadu',
    price_per_day: 3500,
    brand: 'Mahindra',
    model: 'Thar',
    year: 2024,
    fuel_type: 'Diesel',
    transmission: 'Manual',
    seating_capacity: 4,
    vehicle_type: 'SUV',
    mileage_limit: 150,
    amenities: ['4x4', 'Bluetooth', 'AC', 'Off-road Tyres', 'Roof Rack'],
    images: [mahindraThar],
    availability_status: true,
    is_verified: true,
    verified_by: null,
    featured: false,
    rating: 4.8,
    total_reviews: 22,
    views_count: 560,
    booking_count: 38,
    tags: ['suv', '4x4', 'off-road', 'adventure'],
    currency: 'INR',
    latitude: 10.2381,
    longitude: 77.4892,
    discounts: null,
    last_booked_at: daysAgo(3),
    created_at: daysAgo(150),
    updated_at: daysAgo(4),
  },
];

export const DEMO_BIKES: Bike[] = [
  {
    id: 'demo-bike-1',
    host_id: DEMO_HOST_ID,
    title: 'Royal Enfield Classic 350',
    slug: 'royal-enfield-classic-350-kodaikanal',
    description: 'The iconic Royal Enfield Classic 350 — perfect for cruising through Kodaikanal\'s winding hill roads. Recently serviced with new tyres.',
    location: 'Kodaikanal, Tamil Nadu',
    price_per_day: 1200,
    brand: 'Royal Enfield',
    model: 'Classic 350',
    year: 2023,
    engine_capacity: 349,
    vehicle_type: 'Cruiser',
    mileage_limit: 150,
    helmet_included: true,
    images: [royalEnfieldClassic],
    availability_status: true,
    is_verified: true,
    verified_by: null,
    featured: true,
    rating: 4.7,
    total_reviews: 41,
    views_count: 920,
    booking_count: 73,
    tags: ['cruiser', 'hill-ride', 'iconic'],
    currency: 'INR',
    latitude: 10.2381,
    longitude: 77.4892,
    discounts: null,
    last_booked_at: daysAgo(1),
    created_at: daysAgo(200),
    updated_at: daysAgo(3),
  },
  {
    id: 'demo-bike-2',
    host_id: DEMO_HOST_ID,
    title: 'Honda Activa 6G',
    slug: 'honda-activa-6g-kodaikanal',
    description: 'Fuel-efficient and easy-to-ride scooter for city exploration and short hill trips. Great for solo travelers and couples.',
    location: 'Kodaikanal, Tamil Nadu',
    price_per_day: 500,
    brand: 'Honda',
    model: 'Activa 6G',
    year: 2024,
    engine_capacity: 109,
    vehicle_type: 'Scooter',
    mileage_limit: 100,
    helmet_included: true,
    images: [hondaActiva],
    availability_status: true,
    is_verified: true,
    verified_by: null,
    featured: false,
    rating: 4.4,
    total_reviews: 28,
    views_count: 430,
    booking_count: 52,
    tags: ['scooter', 'budget', 'city'],
    currency: 'INR',
    latitude: 10.2381,
    longitude: 77.4892,
    discounts: { weekly: 20 },
    last_booked_at: daysAgo(2),
    created_at: daysAgo(120),
    updated_at: daysAgo(1),
  },
  {
    id: 'demo-bike-3',
    host_id: DEMO_HOST_ID,
    title: 'KTM Duke 390',
    slug: 'ktm-duke-390-kodaikanal',
    description: 'High-performance sports bike for thrill-seekers. Perfect for the 36 hairpin bends of Kodaikanal Ghat Road. Full riding gear available.',
    location: 'Kodaikanal, Tamil Nadu',
    price_per_day: 1800,
    brand: 'KTM',
    model: 'Duke 390',
    year: 2023,
    engine_capacity: 373,
    vehicle_type: 'Sport',
    mileage_limit: 120,
    helmet_included: true,
    images: [ktmDuke],
    availability_status: false,
    is_verified: true,
    verified_by: null,
    featured: false,
    rating: 4.9,
    total_reviews: 15,
    views_count: 380,
    booking_count: 21,
    tags: ['sport', 'adventure', 'ghat-road'],
    currency: 'INR',
    latitude: 10.2381,
    longitude: 77.4892,
    discounts: null,
    last_booked_at: daysAgo(7),
    created_at: daysAgo(90),
    updated_at: daysAgo(7),
  },
];

export const DEMO_EXPERIENCES: Experience[] = [
  {
    id: 'demo-exp-1',
    host_id: DEMO_HOST_ID,
    title: 'Sunrise Trek to Perumal Peak',
    slug: 'sunrise-trek-perumal-peak',
    description: 'A guided early morning trek to the highest point in Kodaikanal at 8,293 ft. Watch the spectacular sunrise over the Western Ghats with hot chai and local snacks.',
    location: 'Kodaikanal, Tamil Nadu',
    price_per_person: 1500,
    category: 'Trekking',
    duration: '5 hours',
    group_size: 12,
    inclusions: ['Professional guide', 'Trekking poles', 'Hot chai & snacks', 'First aid support', 'Photography assistance'],
    exclusions: ['Transport to base', 'Lunch', 'Personal gear'],
    itinerary: [
      { time: '4:30 AM', activity: 'Meet at base camp' },
      { time: '5:00 AM', activity: 'Begin trek through shola forest' },
      { time: '6:30 AM', activity: 'Sunrise at Perumal Peak summit' },
      { time: '7:30 AM', activity: 'Chai break & photo session' },
      { time: '9:00 AM', activity: 'Return to base' },
    ],
    images: [sunriseTrek],
    availability_status: true,
    is_verified: true,
    verified_by: null,
    featured: true,
    rating: 4.9,
    total_reviews: 56,
    views_count: 1450,
    booking_count: 98,
    tags: ['trekking', 'sunrise', 'nature', 'adventure'],
    currency: 'INR',
    latitude: 10.2310,
    longitude: 77.4680,
    discounts: null,
    last_booked_at: daysAgo(1),
    created_at: daysAgo(400),
    updated_at: daysAgo(2),
  },
  {
    id: 'demo-exp-2',
    host_id: DEMO_HOST_ID,
    title: 'Kodaikanal Lake Cycling & Boating',
    slug: 'kodaikanal-lake-cycling-boating',
    description: 'Explore the star-shaped Kodaikanal Lake by bicycle and pedal boat. A relaxing half-day experience with scenic stops for photography and local ice cream.',
    location: 'Kodaikanal, Tamil Nadu',
    price_per_person: 800,
    category: 'Outdoor',
    duration: '3 hours',
    group_size: 8,
    inclusions: ['Bicycle rental', 'Pedal boat (30 min)', 'Guide', 'Ice cream treat', 'Helmet'],
    exclusions: ['Lunch', 'Personal purchases'],
    itinerary: [
      { time: '9:00 AM', activity: 'Bicycle pick-up at lake entrance' },
      { time: '9:30 AM', activity: 'Cycle around the lake (5.5 km)' },
      { time: '10:30 AM', activity: 'Pedal boating on the lake' },
      { time: '11:15 AM', activity: 'Ice cream & photo stop at Bryant Park entrance' },
      { time: '12:00 PM', activity: 'Return bicycles' },
    ],
    images: [lakeCycling],
    availability_status: true,
    is_verified: true,
    verified_by: null,
    featured: false,
    rating: 4.5,
    total_reviews: 38,
    views_count: 720,
    booking_count: 65,
    tags: ['cycling', 'boating', 'lake', 'family-friendly'],
    currency: 'INR',
    latitude: 10.2300,
    longitude: 77.4900,
    discounts: { group: 10 },
    last_booked_at: daysAgo(2),
    created_at: daysAgo(350),
    updated_at: daysAgo(5),
  },
  {
    id: 'demo-exp-3',
    host_id: DEMO_HOST_ID,
    title: 'Night Sky Stargazing Experience',
    slug: 'night-sky-stargazing-kodaikanal',
    description: 'Kodaikanal\'s clear skies make it one of India\'s best stargazing spots. Join us for a guided astronomy session with professional telescopes at Mannavanur Lake.',
    location: 'Kodaikanal, Tamil Nadu',
    price_per_person: 2000,
    category: 'Nature',
    duration: '4 hours',
    group_size: 10,
    inclusions: ['Professional telescope access', 'Astronomy guide', 'Hot chocolate & bonfire', 'Blankets', 'Star map booklet'],
    exclusions: ['Transport to Mannavanur', 'Dinner'],
    itinerary: [
      { time: '7:00 PM', activity: 'Arrival at Mannavanur Lake viewpoint' },
      { time: '7:30 PM', activity: 'Bonfire & hot chocolate' },
      { time: '8:00 PM', activity: 'Telescope setup & constellation intro' },
      { time: '9:30 PM', activity: 'Deep sky object viewing' },
      { time: '10:30 PM', activity: 'Wrap up & departure' },
    ],
    images: [stargazing],
    availability_status: true,
    is_verified: false,
    verified_by: null,
    featured: true,
    rating: 4.8,
    total_reviews: 24,
    views_count: 580,
    booking_count: 42,
    tags: ['stargazing', 'astronomy', 'night', 'nature'],
    currency: 'INR',
    latitude: 10.1800,
    longitude: 77.4700,
    discounts: null,
    last_booked_at: daysAgo(3),
    created_at: daysAgo(200),
    updated_at: daysAgo(8),
  },
];

export const DEMO_BOOKINGS: Booking[] = [
  // Completed bookings
  {
    id: 'demo-booking-1',
    user_id: 'guest-user-1',
    host_id: DEMO_HOST_ID,
    listing_id: 'demo-stay-1',
    listing_type: 'stay',
    start_date: daysAgo(30),
    end_date: daysAgo(27),
    total_price: 10500,
    booking_status: 'completed',
    payment_status: 'completed',
    guests_count: 4,
    currency: 'INR',
    notes: 'Anniversary trip',
    payment_method: 'UPI',
    transaction_id: 'TXN001',
    cancellation_reason: null,
    reviewed: true,
    created_at: daysAgo(35),
    updated_at: daysAgo(27),
  },
  {
    id: 'demo-booking-2',
    user_id: 'guest-user-2',
    host_id: DEMO_HOST_ID,
    listing_id: 'demo-bike-1',
    listing_type: 'bike',
    start_date: daysAgo(20),
    end_date: daysAgo(18),
    total_price: 2400,
    booking_status: 'completed',
    payment_status: 'completed',
    guests_count: 1,
    currency: 'INR',
    notes: null,
    payment_method: 'Card',
    transaction_id: 'TXN002',
    cancellation_reason: null,
    reviewed: true,
    created_at: daysAgo(22),
    updated_at: daysAgo(18),
  },
  {
    id: 'demo-booking-3',
    user_id: 'guest-user-3',
    host_id: DEMO_HOST_ID,
    listing_id: 'demo-exp-1',
    listing_type: 'experience',
    start_date: daysAgo(15),
    end_date: daysAgo(15),
    total_price: 6000,
    booking_status: 'completed',
    payment_status: 'completed',
    guests_count: 4,
    currency: 'INR',
    notes: 'Family trekking group',
    payment_method: 'UPI',
    transaction_id: 'TXN003',
    cancellation_reason: null,
    reviewed: false,
    created_at: daysAgo(18),
    updated_at: daysAgo(15),
  },
  {
    id: 'demo-booking-4',
    user_id: 'guest-user-4',
    host_id: DEMO_HOST_ID,
    listing_id: 'demo-car-1',
    listing_type: 'car',
    start_date: daysAgo(12),
    end_date: daysAgo(9),
    total_price: 5400,
    booking_status: 'completed',
    payment_status: 'completed',
    guests_count: 3,
    currency: 'INR',
    notes: null,
    payment_method: 'Card',
    transaction_id: 'TXN004',
    cancellation_reason: null,
    reviewed: true,
    created_at: daysAgo(14),
    updated_at: daysAgo(9),
  },
  {
    id: 'demo-booking-5',
    user_id: 'guest-user-5',
    host_id: DEMO_HOST_ID,
    listing_id: 'demo-stay-2',
    listing_type: 'stay',
    start_date: daysAgo(8),
    end_date: daysAgo(5),
    total_price: 19500,
    booking_status: 'completed',
    payment_status: 'completed',
    guests_count: 6,
    currency: 'INR',
    notes: 'Corporate offsite',
    payment_method: 'Card',
    transaction_id: 'TXN005',
    cancellation_reason: null,
    reviewed: false,
    created_at: daysAgo(12),
    updated_at: daysAgo(5),
  },
  // Confirmed bookings (upcoming)
  {
    id: 'demo-booking-6',
    user_id: 'guest-user-6',
    host_id: DEMO_HOST_ID,
    listing_id: 'demo-stay-1',
    listing_type: 'stay',
    start_date: daysFromNow(3),
    end_date: daysFromNow(6),
    total_price: 10500,
    booking_status: 'confirmed',
    payment_status: 'completed',
    guests_count: 4,
    currency: 'INR',
    notes: 'Honeymoon trip',
    payment_method: 'UPI',
    transaction_id: 'TXN006',
    cancellation_reason: null,
    reviewed: false,
    created_at: daysAgo(5),
    updated_at: daysAgo(4),
  },
  {
    id: 'demo-booking-7',
    user_id: 'guest-user-7',
    host_id: DEMO_HOST_ID,
    listing_id: 'demo-exp-3',
    listing_type: 'experience',
    start_date: daysFromNow(5),
    end_date: daysFromNow(5),
    total_price: 10000,
    booking_status: 'confirmed',
    payment_status: 'completed',
    guests_count: 5,
    currency: 'INR',
    notes: 'Birthday celebration — stargazing!',
    payment_method: 'Card',
    transaction_id: 'TXN007',
    cancellation_reason: null,
    reviewed: false,
    created_at: daysAgo(3),
    updated_at: daysAgo(2),
  },
  {
    id: 'demo-booking-8',
    user_id: 'guest-user-8',
    host_id: DEMO_HOST_ID,
    listing_id: 'demo-car-2',
    listing_type: 'car',
    start_date: daysFromNow(7),
    end_date: daysFromNow(10),
    total_price: 10500,
    booking_status: 'confirmed',
    payment_status: 'pending',
    guests_count: 2,
    currency: 'INR',
    notes: 'Off-road adventure trip',
    payment_method: null,
    transaction_id: null,
    cancellation_reason: null,
    reviewed: false,
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
  },
  // Pending bookings
  {
    id: 'demo-booking-9',
    user_id: 'guest-user-9',
    host_id: DEMO_HOST_ID,
    listing_id: 'demo-stay-3',
    listing_type: 'stay',
    start_date: daysFromNow(10),
    end_date: daysFromNow(12),
    total_price: 8400,
    booking_status: 'pending',
    payment_status: 'pending',
    guests_count: 2,
    currency: 'INR',
    notes: 'Treehouse experience for our anniversary',
    payment_method: null,
    transaction_id: null,
    cancellation_reason: null,
    reviewed: false,
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: 'demo-booking-10',
    user_id: 'guest-user-10',
    host_id: DEMO_HOST_ID,
    listing_id: 'demo-exp-2',
    listing_type: 'experience',
    start_date: daysFromNow(8),
    end_date: daysFromNow(8),
    total_price: 4800,
    booking_status: 'pending',
    payment_status: 'pending',
    guests_count: 6,
    currency: 'INR',
    notes: 'Family cycling trip with kids',
    payment_method: null,
    transaction_id: null,
    cancellation_reason: null,
    reviewed: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'demo-booking-11',
    user_id: 'guest-user-11',
    host_id: DEMO_HOST_ID,
    listing_id: 'demo-bike-1',
    listing_type: 'bike',
    start_date: daysFromNow(4),
    end_date: daysFromNow(6),
    total_price: 3600,
    booking_status: 'pending',
    payment_status: 'pending',
    guests_count: 1,
    currency: 'INR',
    notes: 'Solo rider, need extra helmet for pillion',
    payment_method: null,
    transaction_id: null,
    cancellation_reason: null,
    reviewed: false,
    created_at: now,
    updated_at: now,
  },
  // Cancelled booking
  {
    id: 'demo-booking-12',
    user_id: 'guest-user-12',
    host_id: DEMO_HOST_ID,
    listing_id: 'demo-stay-2',
    listing_type: 'stay',
    start_date: daysAgo(3),
    end_date: daysAgo(1),
    total_price: 13000,
    booking_status: 'cancelled',
    payment_status: 'refunded',
    guests_count: 5,
    currency: 'INR',
    notes: null,
    payment_method: 'UPI',
    transaction_id: 'TXN012',
    cancellation_reason: 'Change in travel plans',
    reviewed: false,
    created_at: daysAgo(10),
    updated_at: daysAgo(5),
  },
];
