-- Temporarily make host_id nullable for seed data
ALTER TABLE public.stays ALTER COLUMN host_id DROP NOT NULL;

-- Insert homestay data
INSERT INTO public.stays (
  id, title, description, location, price_per_night, currency, amenities,
  images, rating, total_reviews, max_guests, bedrooms, bathrooms,
  property_type, check_in_time, check_out_time, cancellation_policy,
  availability_status, featured, slug
) VALUES
(
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'Cozy Mountain Retreat in Manali',
  'Experience the serenity of the Himalayas in this beautifully designed homestay. Perfect for nature lovers and adventure seekers.',
  'Manali, Himachal Pradesh',
  4500,
  'INR',
  '["WiFi", "Mountain View", "Fireplace", "Kitchen", "Parking", "Heating"]'::jsonb,
  ARRAY['manali-mountain-homestay.jpg'],
  4.8,
  127,
  6,
  3,
  2,
  'Cottage',
  '14:00:00',
  '11:00:00',
  'Free cancellation up to 48 hours before check-in',
  true,
  true,
  'manali-mountain-retreat'
),
(
  'b2c3d4e5-f6a7-8901-bcde-f12345678901',
  'Beachfront Villa in Goa',
  'Luxurious beachfront property with stunning ocean views. Wake up to the sound of waves and enjoy private beach access.',
  'Goa',
  8500,
  'INR',
  '["WiFi", "Beach Access", "Pool", "BBQ Area", "Kitchen", "AC"]'::jsonb,
  ARRAY['goa-beach-villa.jpg'],
  4.9,
  203,
  8,
  4,
  3,
  'Villa',
  '15:00:00',
  '11:00:00',
  'Moderate: 50% refund up to 5 days before check-in',
  true,
  true,
  'goa-beachfront-villa'
),
(
  'c3d4e5f6-a7b8-9012-cdef-123456789012',
  'Heritage Haveli in Jaipur',
  'Step back in time in this beautifully restored traditional Rajasthani haveli. Experience royal hospitality and rich culture.',
  'Jaipur, Rajasthan',
  6500,
  'INR',
  '["WiFi", "Terrace", "Traditional Decor", "Kitchen", "AC", "Cultural Tours"]'::jsonb,
  ARRAY['jaipur-heritage-haveli.jpg'],
  4.7,
  156,
  10,
  5,
  4,
  'Heritage Home',
  '13:00:00',
  '11:00:00',
  'Flexible: Full refund up to 24 hours before check-in',
  true,
  true,
  'jaipur-heritage-haveli'
),
(
  'd4e5f6a7-b8c9-0123-def1-234567890123',
  'Tea Estate Cottage in Munnar',
  'Nestled in lush tea plantations, this charming cottage offers breathtaking views and peaceful surroundings.',
  'Munnar, Kerala',
  5500,
  'INR',
  '["WiFi", "Garden View", "Tea Plantation Tours", "Kitchen", "Bonfire", "Bird Watching"]'::jsonb,
  ARRAY['munnar-tea-cottage.jpg'],
  4.8,
  189,
  5,
  2,
  2,
  'Cottage',
  '14:00:00',
  '10:00:00',
  'Moderate: 50% refund up to 5 days before check-in',
  true,
  false,
  'munnar-tea-cottage'
),
(
  'e5f6a7b8-c9d0-1234-ef12-345678901234',
  'Lakeside Palace View in Udaipur',
  'Romantic lakeside homestay with stunning views of the City Palace. Perfect for couples seeking a magical experience.',
  'Udaipur, Rajasthan',
  7500,
  'INR',
  '["WiFi", "Lake View", "Rooftop Terrace", "AC", "Boat Rides", "Traditional Meals"]'::jsonb,
  ARRAY['udaipur-lakeside-palace.jpg'],
  4.9,
  234,
  4,
  2,
  2,
  'Traditional Home',
  '14:00:00',
  '11:00:00',
  'Moderate: 50% refund up to 5 days before check-in',
  true,
  false,
  'udaipur-lakeside-palace'
),
(
  'f6a7b8c9-d0e1-2345-f123-456789012345',
  'Valley View Home in Kasol',
  'Peaceful retreat in the Parvati Valley. Ideal for backpackers and those seeking tranquility in the mountains.',
  'Kasol, Himachal Pradesh',
  3500,
  'INR',
  '["WiFi", "Valley View", "Trekking Guides", "Bonfire", "Garden", "Parking"]'::jsonb,
  ARRAY['kasol-valley-home.jpg'],
  4.6,
  98,
  4,
  2,
  1,
  'Homestay',
  '13:00:00',
  '11:00:00',
  'Flexible: Full refund up to 24 hours before check-in',
  true,
  false,
  'kasol-valley-home'
)
ON CONFLICT (id) DO NOTHING;